### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by NicoHood** [wesbarnett/snap-sync#50]
Its been a while and a lot of bugs have been fixed since the last release. Maybe you can tag another one?

**Comment by wesbarnett** [comment]
Yes, it's needed. Will do soon.

**Comment by wesbarnett** [comment]
Done.

**Comment by NicoHood** [comment]
@wesbarnett Please checkout my comment on AUR if you missed it: https://aur.archlinux.org/packages/snap-sync/?comments=all
